- name: Run the docker API images
  community.docker.docker_container:
    name: api
    image: mytu/api
    state: started
    restart: true
    ports:
      - "80:80"
    env:
      MONGODB_HOST : "172.17.0.1"
    